version: '3.4'

services:
  php:
    image: api_platform_php
    build:
      context: .
      target: api_platform_php
    #depends_on:
    #  - db
    env_file:
      - .env
    # Comment out these volumes in production
    volumes:
      - .:/srv/api:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw

  api:
    image: api_platform_nginx
    build:
      context: .
      target: api_platform_nginx
    depends_on:
      - php
    # Comment out this volume in production
    volumes:
      - ./public:/srv/api/public:ro
    ports:
      - "8080:80"

volumes:
  db-data: {}
